def menu():

    print("\n===== Patient Management System =====")
    print("1. Add Patient")
    print("2. View Patients")
    print("3. search patient")
    print("4. Delete Patient")
    print("5. Update patient")
    print("6. Statistics")
    print("7. Generate Health Report (PDF)")
    print("8. Add Appointment")
    print("9. View Appointments")
    print("10. Search Appointments")
    print("11. update Appointments")
    print("12. delete Appointments")
    print("13. Predict BMI (Machine Learning)")
    print("14. Exit")