import streamlit as st

from components import (
    load_theme,
    navbar,
    app_sidebar,
    footer
)

from services.settings_service import (
    save_settings,
    load_settings
)

# ==========================================================
# PAGE CONFIGURATION
# ==========================================================

st.set_page_config(
    page_title="Settings",
    page_icon="⚙️",
    layout="wide"
)

load_theme()
app_sidebar()

navbar(
    "Settings",
    "Application Configuration"
)

# ==========================================================
# LOAD SETTINGS
# ==========================================================

settings = load_settings()


if settings:

    (
        clinic,
        dietitian,
        phone_no,
        email_id,
        clinic_address,
        report_title_default,
        footer_default,
        theme_default
    ) = settings

else:

    clinic = ""
    dietitian = ""
    phone_no = ""
    email_id = ""
    clinic_address = ""
    report_title_default = "NutriAyurAI Health Report"
    footer_default = "Generated by NutriAyurAI"
    theme_default = "Light"

# ==========================================================
# PAGE TITLE
# ==========================================================

st.subheader("⚙️ Application Settings")

st.write(
    "Configure your clinic information and application preferences."
)

# ==========================================================
# SETTINGS FORM
# ==========================================================

with st.form("settings_form"):

    st.markdown("## 🏥 Clinic Information")

    clinic_name = st.text_input(
        "Clinic Name",
        value=clinic
    )

    dietitian_name = st.text_input(
        "Dietitian Name",
        value=dietitian
    )

    phone = st.text_input(
        "Phone Number",
        value=phone_no
    )

    email = st.text_input(
        "Email",
        value=email_id
    )

    address = st.text_area(
        "Clinic Address",
        value=clinic_address
    )

    st.markdown("---")

    st.markdown("## 📄 Report Settings")

    report_title = st.text_input(
        "Report Title",
        value=report_title_default
    )

    report_footer = st.text_input(
        "Footer Text",
        value=footer_default
    )

    theme_options = [
        "Light",
        "Dark"
    ]

    if theme_default not in theme_options:
        theme_default = "Light"

    theme = st.selectbox(
        "Application Theme",
        theme_options,
        index=theme_options.index(theme_default)
    )

    save = st.form_submit_button(
        "💾 Save Settings",
        use_container_width=True
    )

# ==========================================================
# SAVE SETTINGS
# ==========================================================

if save:

    save_settings(
        clinic_name,
        dietitian_name,
        phone,
        email,
        address,
        report_title,
        report_footer,
        theme
    )

    st.success("✅ Settings saved successfully!")

    st.rerun()

# ==========================================================
# FOOTER
# ==========================================================

footer()